import{S as v,i as c,a as w}from"./assets/vendor-5401a4b0.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const n of s.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function l(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(e){if(e.ep)return;e.ep=!0;const s=l(e);fetch(e.href,s)}})();const S=document.querySelector(".form"),m=document.createDocumentFragment(),y=document.querySelector(".gallery"),g=document.querySelector(".loader"),i=document.querySelector(".load-more"),h="https://pixabay.com/api/?",o={key:"42159131-e2480a23f0f5c24b1f6f03d93",q:"",image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:1};let p=0;const b={overlayOpacity:.8,captionsData:"alt",captionDelay:250},q=new v(".gallery a",b);S.addEventListener("submit",r=>{r.preventDefault(),y.innerHTML="",o.page=1;const t=document.querySelector("input"),l=t.value.trim();if(!l)c.warning({message:"You forgot to enter your details"});else{u(),o.q=l;const a=h+new URLSearchParams(o);f(a)}t.value=""});const f=async(r,t)=>{await w.get(r).then(({data:l})=>{const a=l.hits;p=l.totalHits,a.length>0?(O(a),window.scrollBy({top:t,behavior:"smooth"})):(u(),c.warning({message:"Sorry, there are no images matching your search query. Please try again!",color:"#f83d04"}))}).catch(l=>{c.warning({message:l})})};function O(r){r.forEach(({webformatURL:t,largeImageURL:l,tags:a,likes:e,views:s,comments:n,downloads:L})=>{const d=document.createElement("li");d.classList.add("gallery-items"),d.insertAdjacentHTML("beforeend",`<a class='gallery-link' href='${l}'>
          <img class='gallery-image' src='${t}' alt='${a}' />
          <ul class='gallery-ul'>
          <li class='gallery-item'><h3 class='gallery-title'>Likes</h3><p class='gallery-value'>${e}</p></li>
          <li class='gallery-item'><h3 class='gallery-title'>Views</h3><p class='gallery-value'>${s}</p></li>
          <li class='gallery-item'><h3 class='gallery-title'>Comments</h3><p class='gallery-value'>${n}</p></li>
          <li class='gallery-item'><h3 class='gallery-title'>Downloads</h3><p class='gallery-value'>${L}</p></li>
        </ul>

        </a>`),m.appendChild(d)}),u(),i.classList.remove("hide"),y.appendChild(m),q.refresh(),P()}i.addEventListener("click",()=>{o.page+=1;const r=h+new URLSearchParams(o);u(),i.classList.add("hide");const t=document.querySelector(".gallery-items").getBoundingClientRect().height*2+26;console.log("Висота дисплея: "+t+"px"),f(r,t)});function u(){g.classList.contains("hide")?g.classList.remove("hide"):(g.classList.add("hide"),i.classList.add("hide"))}function P(){p<o.page*o.per_page&&!i.classList.contains("hide")&&(i.classList.add("hide"),c.info({message:"We're sorry, but you've reached the end of search results."}))}
//# sourceMappingURL=commonHelpers.js.map
